# Runs steps to generate and publish code coverage data

parameters:
  OpenCppCoverageExe: '$(Build.BinariesDirectory)\OpenCppCoverage\OpenCppCoverage.exe'
  GitCommitHash: $(OnnxRuntimeGitCommitHash)
  PublishReport: true
  PostToDashBoard: false
  ContinueOnError: false
steps:

- task: PowerShell@2
  displayName: 'Run Test Coverage'
  inputs:
    filePath: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\run_OpenCppCoverage.ps1'
    arguments: '-OpenCppCoverageExe:"${{parameters.OpenCppCoverageExe}}" -SourceRoot:"$(Build.SourcesDirectory)" -BuildRoot:"$(Build.BinariesDirectory)" -LocalBuild:$false'
  continueOnError: ${{parameters.ContinueOnError}}  

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.BinariesDirectory)/**/cobertura.xml'
    reportDirectory: '$(Build.BinariesDirectory)/**/OpenCppCoverageResults'
  continueOnError: ${{parameters.ContinueOnError}}
  condition: ${{parameters.PublishReport}}

- task: BatchScript@1
  displayName: 'Post code coverage data to the Dashboard'
  inputs:
    filename: '$(Build.BinariesDirectory)\packages\python\python.exe'
    arguments: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\post_code_coverage_to_dashboard.py --commit_hash=${{parameters.GitCommitHash}} --report_file="$(Build.BinariesDirectory)/Debug/Debug/cobertura.xml" --report_url="https://dev.azure.com/onnxruntime/not-a-valid-url-yet"'
    # TODO: As of now I don't have a good way to retrieve the URL of the cobertura.xml report published as a build artifact.
    # For now filling with a stub URL, won't use it in the dashboard
    workingFolder: "$(Build.BinariesDirectory)"
  continueOnError: ${{parameters.ContinueOnError}}
  condition: ${{parameters.PostToDashBoard}}
  