jobs:
- template: templates/win-ci.yml
  parameters:
    AgentPoolWin : 'Linux-CPU'
    JobName: 'Linux_CI_Dev'
    BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--use_mklml --use_tvm --build_wheel"'
    DoNugetPack:  'false'
    ZipDir : 'linux-x64'
    ArtifactName: 'drop-linux'
