
variables:
  doskipv: 'true'

parameters:
  doskipp: 'true'

jobs: 
- job: Linux 
  pool:
    name: Linux-CPU
  timeoutInMinutes: 90
  steps:

  - script: |
     ls
     echo -----
     ls
    displayName: 'step1'
    condition: ne (variables['doskipp'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'step1'
    condition: ne (variables['doskipv'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'Step2'
    condition: always()
