jobs:
- job: Linux_CI_Dev_x86
  pool: Linux-CPU
  steps:
    - template: templates/set-test-data-variables-step.yml

    - task: CmdLine@2
      displayName: 'Clean untagged docker images'
      inputs:
        script: |
          docker rm $(docker ps -a | grep Exited | awk '{print $1;}') || true
          docker container prune -f
          docker image prune -f
        workingDirectory: $(Build.BinariesDirectory)
      continueOnError: true
      condition: always()

    - task: CmdLine@2
      displayName: 'Download azcopy'
      inputs:
        script: |
          curl -so azcopy.tar.gz -L 'https://aka.ms/downloadazcopy-v10-linux'
          tar -zxvf azcopy.tar.gz --strip 1
        workingDirectory: $(Build.BinariesDirectory)

    - task: PythonScript@0
      displayName: 'Download test data'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)/tools/ci_build/github/download_test_data.py'
        arguments: --test_data_url $(TestDataUrl)
        pythonInterpreter: '/usr/bin/python3'
        workingDirectory: $(Build.BinariesDirectory)

    - script: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -a x86 -x "--x86"'
      displayName: 'Command Line Script'

    - script: |
       set -e -x
       mkdir $(Build.BinariesDirectory)/linux-x86
       cp $(Build.BinariesDirectory)/Release/libonnxruntime.so $(Build.BinariesDirectory)/linux-x86
       cd $(Build.BinariesDirectory)
       zip -r linux-x86.zip linux-x86
       cp $(Build.BinariesDirectory/*.zip $(Build.ArtifactStagingDirectory)
       ls -al $(Build.ArtifactStagingDirectory)
      displayName: 'Create Artifacts'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: 'drop-linux'
        targetPath: '$(Build.ArtifactStagingDirectory)'

    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))

    - template: templates/clean-agent-build-directory-step.yml
