

parameters:
  doskipp: 'true'

jobs: 
- job: Linux 
  pool:
    name: Linux-CPU
  timeoutInMinutes: 90

  variables:
    doskipv: 'true'

  steps:

  - ${{ if eq(parameters.doskip, 'false') }}:
  - script: |
     ls
     echo -----
     ls
    displayName: 'step1'

  - script: |
     ls
     echo -----
     ls
    displayName: 'step1'
    condition: ne (variables['doskipv'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'Step2'
    condition: always()
