

parameters:
  doskipp: 'true'

jobs: 
- job: Linux 
  pool:
    name: Linux-CPU
  timeoutInMinutes: 90

  variables:
    doskipv: 'true'

  steps:

  - ${{ if eq(parameters['doskipp'], 'true') }}:
    - task: CmdLine@2
      displayName: 'Clean untagged docker images'
      inputs:
        script: |
          docker rm $(docker ps -a | grep Exited | awk '{print $1;}') || true
          docker container prune -f
          docker image prune -f
        workingDirectory: $(Build.BinariesDirectory)
      continueOnError: true
      condition: always()

    - script: |
       ls
       echo -----
       ls
      displayName: 'step1'

  - script: |
     ls
     echo -----
     ls
    displayName: 'step2'
    condition: ne (variables['doskipv'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'Step3'
    condition: always()
