
parameters:
  doskip: 'true'

jobs: 
- job: Linux 
  pool:
    name: Linux-CPU
  timeoutInMinutes: 90
  steps:

  - script: |
     ls
     echo -----
     ls
    displayName: 'step1'
    condition: ne (variables['doskip'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'Step2'
    condition: always()
