

parameters:
  doskipp: 'true'

jobs: 
- job: Linux 
  pool:
    name: Linux-CPU
  timeoutInMinutes: 90

  variables:
    doskipv: 'true'

  steps:

  - ${{ if eq(parameters['doskipp'], 'true') }}:
    - script: |
       ls
       echo -----
       ls
      displayName: 'step1'

  - script: |
     ls
     echo -----
     ls
    displayName: 'step2'
    condition: ne (variables['doskipv'], 'true')

  - script: |
     ls
     echo -----
     ls
    displayName: 'Step3'
    condition: always()
