jobs:
- job: NuGet_Test_MacOS
  pool: Hosted macOS
  dependsOn:
  - NuGet_Packaging
  condition: succeeded()
  variables:
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
  steps:
  - template: templates/mac-set-variables-and-download.yml

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - Signed NuGet'
    inputs:
      artifactName: 'drop-signed-nuget'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'

  - script: |
     $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
               $(Build.BinariesDirectory)/nuget-artifact \
               $(Build.SourcesDirectory) \
               $(Build.BinariesDirectory) 

     if [ $? -ne 0 ]; then
         echo "Failed to run test"
         exit 1
     fi
    displayName: 'Run Test'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()


