jobs:
- job: NuGet_Test_MacOS
  pool: Hosted macOS
  dependsOn:
  - NuGet_Packaging
  condition: succeeded()
  variables:
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
  steps:
  - task: CmdLine@2
    displayName: 'Download azcopy'
    inputs:
      script: |
        curl -so azcopy.tar.gz -L 'https://aka.ms/downloadazcopy-v10-mac'
        tar -zxvf azcopy.tar.gz --strip 1
      workingDirectory: $(Build.BinariesDirectory)

  - task: PythonScript@0
    displayName: 'Download test data'
    inputs:
      scriptPath: '$(Build.SourcesDirectory)/tools/ci_build/github/download_test_data.py'
      arguments: --test_data_url $(TestDataUrl) --azure_region centralus
      pythonInterpreter: '/usr/local/bin/python3'
      workingDirectory: $(Build.BinariesDirectory)

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - Signed NuGet'
    inputs:
      artifactName: 'drop-signed-nuget'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'

  - script: |
     $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
               $(Build.BinariesDirectory)/nuget-artifact \
               $(Build.SourcesDirectory) \
               $(Build.BinariesDirectory) 

     if [ $? -ne 0 ]; then
         echo "Failed to run test"
         exit 1
     fi
    displayName: 'Run Test'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()


