jobs:
- job: NuGet_Test_Linux
  pool: Linux-CPU
  dependsOn:
  - NuGet_Packaging
  steps:
  - script: |
     set -e -x
     ls -al $(Build.BinariesDirectory)
     rm -rf  $(Build.BinariesDirectory)/*
     ls -al $(Build.BinariesDirectory)
     pushd $(Build.BinariesDirectory)
     curl -so azcopy.tar.gz -L 'https://aka.ms/downloadazcopy-v10-linux'
     tar -zxvf azcopy.tar.gz --strip 1
     /usr/bin/python3 $(Build.SourcesDirectory)/tools/ci_build/github/download_test_data.py --test_data_url "$(TestDataUrl)" 
     popd
     ls -al $(Build.BinariesDirectory)

    displayName: 'Download Test Data'
    env:
      OnnxRuntimeBuildDirectory: $(Build.BinariesDirectory)

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Signed NuGet'
    inputs:
      artifactName: 'drop-signed-nuget'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'

  - script: |
     set -e -x
     $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest-docker.sh $(Build.SourcesDirectory) $(Build.BinariesDirectory) nuget-artifact
    displayName: 'Run Package Test (x64)'
    env:
      OnnxRuntimeBuildDirectory: $(Build.BinariesDirectory)

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
