variables:
  AgentPoolWin : 'Win-CPU'
  AgentPoolLinux : 'Linux-CPU'
  AgentPoolMacOS : 'macOS-10.13'
  Buildcommand : 'Duh'

parameters:
  abc : 'value'

jobs: 
- template: ../win-ci-pipeline.yml
  variables:
    DoDebugBuild: 'false'
    DoNugetPack : 'true'
    DoCompliance: 'true'
    BuildCommand:  '$(Build.SourcesDirectory)\tools\ci_build\build.py --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --cmake_path $(Build.BinariesDirectory)\cmake\bin\cmake.exe --ctest_path $(Build.BinariesDirectory)\cmake\bin\ctest.exe --use_openmp --build_shared_lib --build_csharp --enable_onnx_tests --test_data_url $(TestDataUrl) --test_data_checksum $(TestDataChecksum)'






