# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'
#


jobs: 
- job: myjob
  steps:
    - script: |
       echo helloo
