jobs: 
- template: ../win.yml
  parameters:
    jobname: 'templatejobname'
    sscript: | 
     echo hello
     echo from the uberscript!!
     echo agentpoolwin is $(AGENTPOOLWIN)
     echo binariesdir is $(Build.BinariesDirectory)








